### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by hshah220** [nasa/daa-displays#15]
I am not able to run this project on my local computer. These are the steps I have taken so far:
1. Downloaded the zip, unzip it. In terminal go the daa-displays folder and run the command Make. This resulted in 7 errors in 6 files which were related to the path being incorrect within the files of the folders. I fixed those, and ran the command make. This resulted in several errors which all said that the package found at gov.nasa.larcfm.ACCoRD could not be found. 
2. I cloned the folder from github to my local computer and tried to run the Make command. Still running into the same issues. 

Would anyone be able to assist me?

**Comment by pmasci** [comment]
Hi, thank you for reaching out!
I can help you with this, but need some additional information to debug the problem -- could you please copy/paste the precise error messages you are getting? Also, could you please confirm which operating system are you using?
Thank you,
Paolo

**Comment by hshah220** [comment]
Thank you Paolo for reaching out. I am preparing a report outlining all the steps I have taken so far, as well as the error messages. Once that is done, would it be fine if I send you a link to the document? This way you could understand how I overcame the minor bugs.

**Comment by pmasci** [comment]
Hi, yes, you can send me the document.
Thanks,
Paolo

**Comment by hshah220** [comment]
Please find the document here:
https://wsuidp-my.sharepoint.us/:w:/g/personal/hemilmehul_shah_idp_wichita_edu/EWRvy-szI9JNgLbupthw8Q8BC7-6hgfLqGCciDc-iR2iMg?email=paolo.masci%40nianet.org&e=eagyop

It should contain most of the information. If you require additional information, feel free to reach out to me. 
I appreciate your assistance with this matter.

**Comment by pmasci** [comment]
Hi, I have checked your log file.

The problem is that you are using a Windows machine -- the Makefiles of daa-displays and DAIDALUS (the DAA library used by daa-displays) are designed only for Linux and Mac (see system requirements at https://github.com/nasa/daa-displays#requirements). Using the cygwin environment under Windows does not work either with the makefile that we currently have in daa-displays and DAIDALUS.

The easiest way to resolve this problem is for me to create a compiled distribution of daa-displays + DAIDALUS that you (and others) can download and use as-is, without the need to compile anything. I will do this in the next few days and post a message here with instructions on how to download and execute the compiled package.

Hope this helps.
Thanks,
Paolo

**Comment by hshah220** [comment]
Perfect, thank you! I will also try to get a Mac and try it. I really appreciate your help!

**Comment by hshah220** [comment]
Hi @pmasci I was just wondering if you had a possible timeline on the previous resolution for a windows computer? I am simply asking so that I can check on it later.

**Comment by pmasci** [comment]
Hi, please try the compiled version at the following link: https://drive.google.com/drive/folders/1N2355MvwyAkrWx1hw3HF2rJGe3scJP_z?usp=sharing

To run the compiled version on Windows:
1. Decompress the zip file.
2. Open a terminal window and run the following command to launch the DAA-Displays server: 
`cd daa-displays && restart.bat`
>NOTE: Keep the terminal window open otherwise the server will be terminated.
3. Open a Web Browser at http://localhost:8082. This will open the DAA-Displays front-end.

Thanks,
Paolo

**Comment by hshah220** [comment]
Hello @pmasci 

Thank you for your quick response regarding this matter. I have been going through it, and from what I can tell, it works. There is a glitch with the 3d-view part of the application though. It appears as a blank screen on any of the scenario files loaded. 
Would it be possible for you to take a look at it?

Also I had a couple of follow-up questions. 
1. If I were to upload my own scenario file in the existing format from the previous files, would it be able to load it? Basically, can I customize the application to run a file that I upload?
2. Is it possible to run the application as a stand-alone application, and not from the localhost? This is to see if it can be integrated with other applications such as MatLab and so on.

I understand that these things might take time, so I will work with the current version and get started. 

Thank you once again. Please let me know if I can be of assistance.

**Comment by pmasci** [comment]
Hi,
- Yes, you can add new scenarios in .daa format. You can copy your .daa files directly in the `daa-displays/daa-scenarios/` folder -- reload the tool and you will see them in the list of available scenarios. You can also load the .daa files directly from the views, using the "browse" button located in the left panel of each few, next to the label "Scenarios". The .daa files are text files, where each row indicates the tail number, location (lat, lon, alt) and velocity vector of an aircraft at a given time instant. The first aircraft is the ownship.
- Yes, the views can be compiled into stand-alone applications and connected to external tools and flight simulators. We will be releasing an open source stand-alone DANTi application in the coming months.

I will take a look at the 3D-view and post a message here for the fix.
Thanks,
Paolo

**Comment by pmasci** [comment]
Hi, I have fixed the problem with the 3D view and uploaded a new zip file `daa-display-1.0.15-universal-compiled-V1.zip` at https://drive.google.com/drive/folders/1N2355MvwyAkrWx1hw3HF2rJGe3scJP_z?usp=sharing

Thanks,
Paolo

**Comment by hshah220** [comment]
Thank you Paolo for the updates. I apologize for the delay in reaching out. I have tested the application, and so far everything looks like it is working great. I think the issue is considered resolved. However, I was wondering if you had any documentation on how we could integrate this tools and views created in external tools and flight simulators. If not, I understand, and I will wait for future updates.

**Comment by pmasci** [comment]
A stand-alone version of the daa-display that can be integrated with external tools and flight simulators is now available at this link: https://github.com/nasa/DANTi
