### ISSUE TITLE
scenario-files not available

### ISSUE THREAD

**Issue by marselomeri** [nasa/daa-displays#6]
Hello, 
I could not find the scenario files described in the Examples (1, 2). 
Thanks

**Comment by pmasci** [comment]
Hi, you can find the scenarios files at the following link:
https://github.com/nasa/daa-displays/tree/46c4ff0fc34c73431bec67a47f8ca5f789939971/src/daa-scenarios

Download the .daa files and save them in daa-displays/dist/daa-scenarios/

Hope this helps!

**Comment by marselomeri** [comment]
Yes that is helpful! Thanks!
